[tool.pyright]
reportGeneralTypeIssues = false
reportPrivateImportUsage = false

[tool.isort]
line_length = 120
indent = '    '
lines_after_imports = 2

[tool.mypy]
disable_error_code = "no-redef"

ignore_missing_imports = true

[tool.pylint.MASTER]
load-plugins = "pylint_behave"

init-hook='import sys; sys.path.append(".")'

[tool.pylint.messages_control]
max-line-length = 120

[tool.brunette]
line-length = 120
